package model

// AllModels returns GORM entities for AutoMigrate.
func AllModels() []any {
	return []any{
		&User{},
		&DataSource{},
		&Article{},
		&Topic{},
		&AlertRule{},
		&AlertRecord{},
		&CrawlerSpiderConfig{},
		&CrawlerRunLog{},
		&Report{},
		&SystemSetting{},
		&SystemSettingHistory{},
		&ConfigSnapshot{},
		&AuditLog{},
		&RagSyncLog{},
		&ChatSession{},
		&ChatMessage{},
		// MediaCrawler 平台表
		&BilibiliVideo{},
		&BilibiliVideoComment{},
		&BilibiliUpInfo{},
		&BilibiliContactInfo{},
		&BilibiliUpDynamic{},
		&DouyinAweme{},
		&DouyinAwemeComment{},
		&DyCreator{},
		&KuaishouVideo{},
		&KuaishouVideoComment{},
		&WeiboNote{},
		&WeiboNoteComment{},
		&WeiboCreator{},
		&XhsCreator{},
		&XhsNote{},
		&XhsNoteComment{},
		&TiebaNote{},
		&TiebaComment{},
		&TiebaCreator{},
		&ZhihuContent{},
		&ZhihuComment{},
		&ZhihuCreator{},
		// 工作流表
		&Workflow{},
		&WorkflowExecution{},
		&WorkflowNodeExecution{},
	}
}
