server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Admin SPA — 所有 /admin/* 回退到 /admin/index.html
    location /admin/ {
        try_files $uri $uri/ /admin/index.html;
    }

    location = /admin {
        return 301 /admin/;
    }

    gzip on;
    gzip_types text/plain application/javascript application/json text/css;
    gzip_min_length 1024;
}
